baseURL = 'https://rupaben-odedara.netlify.app/'
languageCode = 'en-us'
title = 'Rupaben Odedara Portfolio'
[params]
  customSCSS = ["css/_main.scss"]
  footer_mail_work = "rupaben.odedara04@gmail.com"
  footer_mail = "odedararupa35@gmail.com"
  facebook = "https://www.facebook.com/rupa.odedara"
  github = "https://github.com/OdedaraRupa"
  linkedin = "https://www.linkedin.com/in/rupaben-odedara/"
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)

  

#Hugo version = 0.144.1



# main menu

[menu]
    ## Menu bar
    [[menu.main]]
      url = "/"
      name = "Home"
      weight = 1

    [[menu.main]]
      url = "/about/"
      name = "About"
      weight = 2

    [[menu.main]]
      url = "/contact/"
      name = "Contact"
      weight = 3

    [[menu.main]]
      url = "/portfolio/"
      name = "Portfolio"
      weight = 4

    [[menu.footer]]
      url = "/"
      name = "Home"
      weight = 1

    [[menu.footer]]
      url = "/contact/"
      name = "Contact"
      weight = 2
      
    [[menu.footer]]
      url = "/about/"
      name = "About"
      weight = 3
   